### PR TITLE
Fix inconsistency between table and scroller state

### PR DESCRIPTION
**Pull request by ypnos-web**
Hello,

when you use Scroller with state saving, Scroller saves the current position (pixel and row) on every **scroll**. However, the starting position is only saved on every **draw**. This can lead to an inconsistent state.

**Example:** http://live.datatables.net/tahulule/1/edit
This example is the Scroller server side example with added stateSave: true option.

**To reproduce:**
1. Scroll to an arbitrary position
2. Scroll a bit further (NOT triggering a redraw)
3. Reload
4. Scroll a bit further (NOT triggering a redraw)
5. Reload

**Effect:** After the second reload, or maybe third if you didn't scroll far, you will see an empty display.

The reason is that start in the saved state is never updated, so iScrollerTopRow will grow beyond start + length. Also note, that Scroller uses topRowFloat (derived from iScrollerTopRow) to determine when redrawing is needed which does not reflect the real table display (controlled by _iDisplayStart).

This fix ensures that records start matches scrolling position to avoid them diverging. Whenever the user gets back to the table, the initially loaded data perfectly fits the Scroller state.

I provide my changes to you as public domain. Feel free to publish under MIT license.

### CODE REVIEW

**Comment by DataTables** [comment]
Thanks for this! I'm afraid I'm rushing out the door atm, but I'll take a look at the changes next week.

**Comment by ypnos-web** [comment]
Did you get a chance to look into this?

**Comment by DataTables** [comment]
Sorry - not yet. Other things keep popping up. I'll reply back when I do. Its in my inbox so I won't forget.

**Comment by ypnos-web** [comment]
This problem still exists and actually got much worse. Now, in the example as I layed out above (http://live.datatables.net/tahulule/1/edit), already a single small scroll before reloading the page will lead to an empty table after reloading the page.

**Comment by ypnos** [comment]
Sorry I did not express it clearly. You need only the first three steps:

1. Scroll to an arbitrary position (e.g. by moving scrollbar directly)
2. Scroll a bit further (NOT triggering a redraw)
3. Reload

**Comment by ypnos-web** [comment]
Sorry I did not express it clearly. You need only the first three steps:

1. Scroll to an arbitrary position (e.g. by moving scrollbar directly, triggering a redraw)
2. Scroll a bit further (NOT triggering a redraw)
3. Reload

**Comment by DataTables** [comment]
Thanks - I'm with you now! I've added it to the list of things to fix for the next release of Scroller.

I don't believe that the issue is that the start position is saved only on draw, since the start position is only changed on draw. I'm not certain what is causing it yet though.

**Comment by ypnos-web** [comment]
The problem is **divergence** between:
1. start position which is only saved on draw()
2. scroller state which is saved on scroll()
https://github.com/DataTables/Scroller/blob/1b0fe553df598783926f843da04b00f12f4abf8f/js/dataTables.scroller.js#L744-L745

I hope this is helpful for your bug hunting.

**Comment by DataTables** [comment]
Finally got to the bottom of it. The virtual scrolling calculations for large data sets was wrong! Addressing that fixed it.

**Pull request closed without merging**
